### ISSUE TITLE
Build instructions missing

### ISSUE THREAD

**Issue by dvdmunckhof** [n3r4zzurr0/range-slider-input#2]
Build steps and build dependencies seem to be missing from the `package.json` file. Could you provide build instructions?

I tried: (copied from https://github.com/n3r4zzurr0/react-range-slider-input/blob/master/package.json)
```sh
NODE_ENV=production babel src --out-dir dist --copy-files
```

However, the results did not match the contents of the npm package.

The reason I ask, is I wrote TypeScript type declarations that I'd like to contribute back to the project. By the way, awesome library! :)

**Comment by n3r4zzurr0** [comment]
I have added the [`build instructions`](https://github.com/n3r4zzurr0/range-slider-input/blob/main/package.json).
...
Sorry for the delay, I was heavily engaged in some other work.
Would love to have a contributor.

**Comment by dvdmunckhof** [comment]
Thanks for adding the build instructions, it was very easy to build! I just created a [pull request](https://github.com/n3r4zzurr0/range-slider-input/pull/4) with my TypeScript type declarations 😄
