### ISSUE TITLE
Event listeners are never removed

### ISSUE THREAD

**Issue by dvdmunckhof** [n3r4zzurr0/range-slider-input#3]
As the titles says, (global) event listeners are never removed. In case you want to dynamically add or remove the range slider, the listeners need to be removed.

I suggest to provide a method (like `destroy()` or `unregister()`), which unregisters the event listeners. That method should be called if somebody wants dynamically remove the slider.

**Comment by n3r4zzurr0** [comment]
I have added a return value property named `removeGlobalEventListeners()`.
Thanks for the suggestion.

**Comment by dvdmunckhof** [comment]
Looks good, thank you for implementing this!
