### ISSUE TITLE
Callback examples ?

### ISSUE THREAD

**Issue by bakman2** [n3r4zzurr0/range-slider-input#5]
Many thanks for this work, in general it works nicely.

I am a bit confused how I can read the values when they are changed by the user or how to set them programmatically.
Are there any callback functions ? The documentation describes something with onInput, but I don't really understand how it is used.

Could you provide additional examples ?

**Comment by bakman2** [comment]
I got the value out of it, not sure if this is right way to do it:

```
  const slide = rangeSlider(document.querySelector(".range-slider"), {
        value: [0, 10],
        step: "any",
        thumbsDisabled: [true, false],
        rangeSlideDisabled: true,
        onInput: v => {
          console.log(Math.floor(v[1]))
        },
      })

```

**Comment by n3r4zzurr0** [comment]
Yes, `onInput` is called whenever a value is modified upon user interaction or when `min()`, `max()`, `step()` or `value()` are called. So, you are doing it right.

And, to set the value programmatically, you can use the [`value()`](https://github.com/n3r4zzurr0/range-slider-input#min-max-step-value-and-orientation) function.

**Comment by bakman2** [comment]
Indeed, I am looking for a way to "mute" onInput when the `value()` is called programmatically. ie. 
when a user changes the slider, fire.
when it is programmatically set, mute (or have some flag available that indicate who changed it).

**Comment by n3r4zzurr0** [comment]
Oh okay, now I get it.

There wasn't any way to differentiate between the two in the current scheme. So, I have added a second parameter to the `onInput` function and have published a new version.

```js
rangeSlider(element, {
  onInput: (value, userInteraction) => {
    if(userInteraction) {
      console.log("value modified upon user interaction")
    }
  }
})
```

**Comment by bakman2** [comment]
Many thanks, works great! Time to play some more, thanks for the quick support!
