### ISSUE TITLE
Add support for css transform (scale) on container

### ISSUE THREAD

**Issue by vincentwinkel** [n3r4zzurr0/range-slider-input#7]
It currently doesnt support the css transform (scale) property on the container. Meaning that if we apply a transform, the thumbs dont follow the mouse with accuracy.
For example, in my case, I try to integrate the slider in a node from React Flow.

The native `<input type="range"/>` works correctly tho.

**Comment by n3r4zzurr0** [comment]
I have replaced some properties (`clientWidth`, `clientHeight`, `offsetLeft`, etc.) which didn't get affected by transforms, with `getBoundingClientRect()` properties and have published a new version. It should be working now!

**Comment by vincentwinkel** [comment]
Amazing, it works like a charm, thank you!
